### ISSUE TITLE
那个大哥你知道你readme乱码了吗

### ISSUE THREAD

**Issue by Haocen2004** [MX233/Mirai-MCPingPlugin#4]

**Comment by Pmaru-top** [comment]
不知道

**Comment by Pmaru-top** [comment]
但是我这边使用手机和电脑都显示正常,我朋友也表示README没问题

**Comment by Haocen2004** [comment]
![Screenshot_20210816-012012.png](https://user-images.githubusercontent.com/25221696/129486826-b8546956-1f56-49f9-a1f4-7023c6f11134.png)

**Comment by Haocen2004** [comment]
就很奇怪 手机github客户端打开就乱码 切浏览器就不会
