### ISSUE TITLE
服务器有效 发送查询失败

### ISSUE THREAD

**Issue by M-Crowe** [MX233/Mirai-MCPingPlugin#6]
![image](https://user-images.githubusercontent.com/77571440/130610083-f29670d6-2054-40ad-84ae-b2cb53c7cb41.png)

**Comment by Pmaru-top** [comment]
本来想更好判定服务器无效,翻车了那就改回来好了
已修复,下载:
https://github.com/MX233/Mirai-MCPingPlugin/releases/tag/v2.0-Beta.3

**Comment by M-Crowe** [comment]
![5L5%9O92BV(W@~B5TN$L`}N](https://user-images.githubusercontent.com/77571440/130985913-a2f17ea7-ee92-4699-a47a-38b0f30d1ff7.gif)
