### ISSUE TITLE
读写Config.json时因相对路径问题报错

### ISSUE THREAD

**Issue by wpcwzy** [MX233/Mirai-MCPingPlugin#7]
![QQ图片20210830002502](https://user-images.githubusercontent.com/16263217/131257794-e7e08a4d-0623-4885-8636-7480fef71a58.png)

如截图所示
Remirai脚本内容：
```
@echo off
title mirai
set p="%cd%\jre\bin"
set path=%p%;%path%
:begin
cd C:\Users\Administrator\Desktop\Programs\mirai_2.4.1_native2.0.0
java -cp "./libs/*" -Dmirai.slider.captcha.supported net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader %*

goto begin
```

**Comment by Pmaru-top** [comment]
## 更新了下配置路径获取方式

    String directory;
    this.getLogger().info("配置文件路径: " + (directory = this.getDataFolder().getAbsoluteFile().getPath()));
    configFilePath = directory + "\\Config.yml";
    jeTypesetFilePath = directory + "\\typeset.txt";
    beTypesetFilePath = directory + "\\Betypeset.txt";

[MCPingV2.1](https://github.com/MX233/Mirai-MCPingPlugin/releases/tag/v2.1)

希望行了

**Comment by wpcwzy** [comment]
解决了，谢谢
